version: "3.8"
services:
  users-db:
    container_name: users_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - users-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_db_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d user_db -U user_db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  products-db:
    container_name: products_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - products-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=product_db_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=product_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d product_db -U product_db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-db:
    container_name: orders_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - orders-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=order_db_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=order_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d order_db -U order_db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./src/user_service
    restart: on-failure
    container_name: user_service
    command: sh -c "cd src/user_service && go install && user_service"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://user_db_user:1234@users-db/user_db?sslmode=disable
      - CGO_ENABLED=1
  
  product-service:
    build: ./src/product_service
    restart: on-failure
    container_name: product_service
    command: sh -c "cd src/product_service && go install && product_service"
    volumes:
      - .:/code
    ports:
      - 8002:8000
    depends_on:
      products-db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://product_db_user:1234@products-db/product_db?sslmode=disable
      - CGO_ENABLED=1
  
  order-service:
    build: ./src/order_service
    restart: on-failure
    container_name: order_service
    command: sh -c "cd src/order_service && go install && order_service"
    volumes:
      - .:/code
    ports:
      - 8003:8000
    depends_on:
      orders-db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://order_db_user:1234@orders-db/order_db?sslmode=disable
      - CGO_ENABLED=1

volumes:
  users-db:
  products-db:
  orders-db: